# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            eric<br/>toulson
tagline:          ''
description:      ''
url:              ''

author:
  name:           'Eric Toulson'

paginate:         5
