# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            erictoulson
tagline:          ''
description:      ''
url:              ''

author:
  name:           'Eric Toulson'

paginate:         3
