# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            erictoulson
tagline:          ''
description:      ''
url:              ''

author:
  name:           'Eric Toulson'

paginate:         3

gems:             [jekyll-paginate]

redcarpet:
  extensions: []